
package com.kthree.ws.service.calc;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Calculator", targetNamespace = "http://calc.service.ws.kthree.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Calculator {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://calc.service.ws.kthree.com/", className = "com.kthree.ws.service.calc.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://calc.service.ws.kthree.com/", className = "com.kthree.ws.service.calc.AddResponse")
    @Action(input = "http://calc.service.ws.kthree.com/Calculator/addRequest", output = "http://calc.service.ws.kthree.com/Calculator/addResponse")
    public int add(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sub", targetNamespace = "http://calc.service.ws.kthree.com/", className = "com.kthree.ws.service.calc.Sub")
    @ResponseWrapper(localName = "subResponse", targetNamespace = "http://calc.service.ws.kthree.com/", className = "com.kthree.ws.service.calc.SubResponse")
    @Action(input = "http://calc.service.ws.kthree.com/Calculator/subRequest", output = "http://calc.service.ws.kthree.com/Calculator/subResponse")
    public int sub(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
